#!/bin/sh

# Release the current branch to one of the following branches:
# 1. develop
# 2. test
# 3. staging
# 4. main
# 5. release (default)

# Get the current branch name
current_branch=$(git branch --show-current)
release_branch="release"

# If there is an argument, use it as the release branch
if [ "$1" != "" ]; then
  release_branch="$1"
fi

echo "Releasing $current_branch to $release_branch"

# Checkout the branch from argument
git checkout "$release_branch"

# Merge the current branch into the branch from argument
git merge "$current_branch"

# Push the branch from argument to origin
git push origin "$1"

# Checkout the current branch
git checkout "$current_branch"

