#!/bin/sh

# Release the current branch to one of the following branches:
# 1. develop
# 2. test
# 3. staging
# 4. main
# 5. release (default)

# Get the current branch name
current_branch=$(git branch --show-current)

# Checkout the branch from argument
git checkout "$1"

# Merge the current branch into the branch from argument
git merge "$current_branch"

# Push the branch from argument to origin
git push origin "$1"

# Checkout the current branch
git checkout "$current_branch"

